### ISSUE TITLE
Translation from English into English

### ISSUE THREAD

**Issue by Tagalskiy** [ParisNeo/prompt_translator#5]
It would be nice to have a minimal setting, for example, to be able to turn off the translation of a negative prompt, I have a negative prompt in English already fixed in the ui-config.json file. I think you need to remove the translation from English to English, it does not happen correctly. I write a prompt in my native language, but I add specific terms in English, as a result of the translation, the wrong prompt is obtained. How to remove an extension? Where is the Downloading pytorch_model.bin file located: 100%| 2.44G/2.44G ?

**Comment by ParisNeo** [comment]
OK, I'll add this. Nice Idea. 
As for the bin file it should be downloaded to your transformers cache directory.
Generally in your home folder /.cache/torch/transformers/
Maybe I should download the model to a local folder for example. That would be eazier to users if they want to uninstall the extension.
I'll remove english from the list. If you use english, just disable the extension.
Actually, this tool uses MBART50 locally on your PC which is cool, since you don't use any internet service and it is 100% free and open source.

Thank you for the comment

**Comment by ParisNeo** [comment]
I have adressed all the issues you mensioned:
- The model is now downloaded to a subfolder called model in the extension directory, so that it gets removed if you uninstall the extension
- English is removed from the list
- Now you can enable or not the negative prompt translation
Thank you for your valuable comment

**Comment by Tagalskiy** [comment]
Thanks, but after installing your extension, right after launching my Stable Diffusion refuses to work, in the console there is an error:

Traceback (most recent call last):
  File "G:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "G:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "G:\AI\SD\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1377, in preprocess
    return self.choices.index(x)
ValueError: '' is not in list

 After removing the extension, everything works as before.

**Comment by ParisNeo** [comment]
I'll look it up right now and tell you what's wrong.

**Comment by ParisNeo** [comment]
Hi and thank you for pointing this out.
I forgot to select a default language that is not English. On py PC it works because I have already run this before so the last language is selected that's why I didn't see it.

I have patched the code and it should work.
Let me know if it works for you

**Comment by Tagalskiy** [comment]
Thanks, everything seems to be working now )

**Comment by ParisNeo** [comment]
Happy that it works for you. And again, thanks for pointing out the errors. It helped enhancing the tool.
